# Chat Filter by _txsla and NBT Archives
# This plugin uses MiniMessage to parse messaged


# For compatibility with other chat plugins
event-priority: normal

# [   ENABLE FILTER CATEGORIES ]
# Add a category here to enable it
# Permission 'chatfilter.regex.bypass' will bypass this filter
# Messages are filtered from first category in this list to last, so if two filters both match the pattern [a-zA-Z]\.(\.com|\.net), only the one listed first will be triggered
# The 'gamersafer' list is the official list of GamerSafer.com
enabled-categories:
  - 'example1'
  - 'example2'
  - 'gamersafer'


# [  SPAM LIMITER   ]
# Every time a player sends a message, it increments a counter
# Every x milliseconds that counter is decremented
# If a player hits the max messages on their counter, their messages are not shown to other players
# Permission `chatfilter.spam.bypass` will bypass this filter
spam-limiter:
  enabled: true
  count-repeats: true # should repeat messages increment twice?
  counter-ceiling: 4 # if a player's message counter goes above this number, their messages will be hidden to other players
  decrement-timer: 4000 # milliseconds between message counter decrements


# [   NOTIFY   ]
# Notify and admin when someone triggers a filter
# Players with permission 'chatfilter.notify' will be notified
# Placeholders:
# %PLAYER% - violator's username
# %MESSAGE% - message that triggered the filter
# %CATEGORY% - filter category that got triggered
notify:
  enabled: false
  message: '<red>%PLAYER% has violated %CATEGORY% with message %MESSAGE%</red>'


# logs violations
log:
  to-file: true
  to-discord: false
  webhook: "webhook"

# Mute settings
mute:
  # should mods be required ot provide a reason?
  require-reason: true
  # show muted player's their messages
  ghost-player: true
  # How does your chat plugin format messages? - this is for ghosting players
  # Placeholders:
  # %PLAYER% - player who sent the message
  # %MESSAGE% - player's message
  message: "<white><%PLAYER%> %MESSAGE%</white>"




  # enable debug console output
  debug: false